Repository mluzarow/MangoBango, pull requests merged in 2018-07, with the labels that each got.

#43 WIP: Account Management - made meta page more customizable
  app/Core/MetaPage.php
  app/index.php
Labels: enhancement

#41 Account Management - Created login view
  app/Core/MetaPage.php
  app/ViewItems/CSS/Login.css
  app/ViewItems/JS/Login.js
  app/ViewItems/PageViews/LoginView.php
Labels: enhancement

#46 User Accounts - Added password validation
  app/Core/AJAXProcessor.php
  app/Core/SessionManager.php
  app/ViewItems/JS/Login.js
  app/index.php
Labels: enhancement

#48 User Accounts - Added login page controller
  app/Controllers/Login.php
  app/Core/SessionManager.php
Labels: enhancement

#49 User Accounts - Add user sessions
  app/Controllers/Login.php
  app/Core/SessionManager.php
  app/ViewItems/CSS/Login.css
  app/ViewItems/CSS/UIFrame.css
  app/ViewItems/JS/dropdown.js
  app/ViewItems/JS/logout.js
  app/ViewItems/PageViews/MetaView.php
  app/index.php
Labels: enhancement

#51 Bug (DB Viewer): Updated oldstyle views
  app/DBViewer/Controller/DBViewerMain.php
  app/DBViewer/PageControllers/Dashboard.php
  app/DBViewer/PageControllers/Table.php
  app/DBViewer/Views/DashboardView.php
  app/DBViewer/Views/TableView.php
Labels: bug

#52 First time setup page
  app/Controllers/FirstTimeSetup.php
  app/Core/SessionManager.php
  app/ViewItems/CSS/FirstTimeSetup.css
  app/ViewItems/JS/FirstTimeSetup.js
  app/ViewItems/PageViews/FirstTimeSetupView.php
  app/resources/icons/loading_spinner_200px.gif
Labels: enhancement

#53 Bug (Reader): Fixed issue with page view chapter transitions
  app/Controllers/Reader.php
  app/ViewItems/CSS/ReaderPage.css
  app/ViewItems/JS/ReaderPage.js
  app/ViewItems/PageViews/ReaderPageView.php
  app/ViewItems/PageViews/ReaderStripView.php
Labels: bug

#62 Added message when the library is empty
  app/ViewItems/CSS/DisplayLibrary.css
  app/ViewItems/PageViews/DisplayLibraryView.php
Labels: bug

#63 Misc first time setup bug fixes
  app/Controllers/FirstTimeSetup.php
  app/Core/Database.php
  app/ViewItems/PageViews/ConfigView.php
  app/index.php
Labels: bug, enhancement

#64 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#66 Issue #59 take 2
  app/Core/Database.php
  app/server.ini
Labels: bug, good first issue

#67 Lazy Loading - Added lazy load controller
  app/Core/LazyLoader.php
  app/resources/icons/placeholder.svg
Labels: enhancement, project task

#71 Lazy Loading - Added lazy loader js script
  app/ViewItems/JS/DisplayLibrary.js
  app/ViewItems/JS/DisplaySeries.js
  app/ViewItems/JS/LazyLoader.js
  app/ViewItems/JS/ReaderPage.js
  app/ViewItems/JS/ReaderStrip.js
Labels: enhancement, project task

#68 Lazy Loading - Edited library controllers to prep image paths
  app/Controllers/DisplayLibrary.php
  app/Controllers/DisplaySeries.php
  app/Controllers/Reader.php
  app/Core/LazyLoader.php
Labels: enhancement, project task

#69 Lazy Loading - Updated views with lazy loading
  app/ViewItems/CSS/DisplayLibrary.css
  app/ViewItems/CSS/DisplaySeries.css
  app/ViewItems/CSS/ReaderPage.css
  app/ViewItems/CSS/ReaderStrip.css
  app/ViewItems/JS/ReaderPage.js
  app/ViewItems/PageViews/DisplayLibraryView.php
  app/ViewItems/PageViews/DisplaySeriesView.php
  app/ViewItems/PageViews/ReaderPageView.php
  app/ViewItems/PageViews/ReaderStripView.php
  app/resources/icons/loading-3s-200px.svg
  app/resources/icons/loading_spinner_200px.gif
Labels: enhancement, project task

#74 Bug - Fixed jumping series covers
  app/ViewItems/CSS/DisplaySeries.css
Labels: bug, good first issue

#75 Metadata Matching - Added metadata grab to page controller / view
  app/Controllers/DisplaySeries.php
  app/ViewItems/PageViews/DisplaySeriesView.php
Labels: enhancement, project task
