Repository mluzarow/MangoBango, pull requests merged in 2018-10, with the labels that each got.

#87 Un-abstract view parent
  app/ViewItems/PageViews/ConfigView.php
  app/ViewItems/PageViews/DisplayLibraryBookcaseView.php
  app/ViewItems/PageViews/DisplayLibraryView.php
  app/ViewItems/PageViews/DisplaySeriesView.php
  app/ViewItems/PageViews/FirstTimeSetupView.php
  app/ViewItems/PageViews/HomeView.php
  app/ViewItems/PageViews/LoginView.php
  app/ViewItems/PageViews/MetaView.php
  app/ViewItems/PageViews/ReaderPageView.php
  app/ViewItems/PageViews/ReaderStripView.php
  app/ViewItems/ViewTemplate.php
Labels: refactor

#89 Fixed placeholder cover height
  app/ViewItems/CSS/DisplaySeries.css
Labels: refactor

#91 Fixed lazy loading timeouts
  app/Core/LazyLoader.php
  app/ViewItems/JS/DisplayLibrary.js
  app/ViewItems/JS/DisplaySeries.js
  app/ViewItems/JS/LazyLoader.js
  app/ViewItems/JS/LazyLoaderEvents.js
  app/ViewItems/JS/ReaderPage.js
  app/ViewItems/JS/ReaderStrip.js
  app/ViewItems/PageViews/DisplayLibraryView.php
  app/ViewItems/PageViews/DisplaySeriesView.php
  app/ViewItems/PageViews/ReaderPageView.php
  app/ViewItems/PageViews/ReaderStripView.php
Labels: bug, refactor

#92 Fixed a couple importing issues
  app/Controllers/Config.php
  app/Controllers/DisplaySeries.php
Labels: bug

#94 Removed old series cover spot
  app/ViewItems/CSS/DisplaySeries.css
  app/ViewItems/PageViews/DisplaySeriesView.php
Labels: refactor

#93 Fixed issue with missing series covers
  app/ViewItems/PageViews/DisplayLibraryView.php
Labels: bug

#96 Added editor config
  .editorconfig
Labels: enhancement, request

#97 Added CircleCI config
  .circleci/config.yml
  README.md
Labels: enhancement

#99 Replaced JS script reroutes with PHP redirects
  app/Controllers/Login.php
  app/index.php
Labels: refactor

#100 Added view service
  app/Services/Data/IViewData.php
  app/Services/Data/ViewItem.php
  app/Services/View/Controller.php
  app/Services/View/Factory.php
  app/Services/View/Provider.php
  app/Services/View/Service.php
Labels: enhancement, refactor

#101 Moved Data classes into the correct folder
  app/Services/View/Data/IViewData.php
  app/Services/View/Data/ViewItem.php
Labels: bug

#102 Corrected bad types in view service
  app/Services/View/Provider.php
Labels: bug

#103 Added HTML files for all the views
  app/ViewItems/HTML/Config.php
  app/ViewItems/HTML/DisplayLibrary.php
  app/ViewItems/HTML/DisplaySeries.php
  app/ViewItems/HTML/FirstTimeSetup.php
  app/ViewItems/HTML/Home.php
  app/ViewItems/HTML/Login.php
  app/ViewItems/HTML/ReaderPage.php
  app/ViewItems/HTML/ReaderStrip.php
Labels: refactor

#104 Added data objects for view service
  app/Services/View/Data/Config.php
  app/Services/View/Data/DisplayLibrary.php
  app/Services/View/Data/DisplaySeries.php
  app/Services/View/Data/Home.php
  app/Services/View/Data/ReaderPage.php
  app/Services/View/Data/ReaderStrip.php
Labels: refactor

#105 Removed DB viewer files
  app/DBViewer/PageControllers/Dashboard.php
  app/DBViewer/PageControllers/Table.php
  app/DBViewer/Views/DashboardView.php
  app/DBViewer/Views/TableView.php
  app/index.php
Labels: refactor

#106 Added metaview to view service.
  app/Services/View/Data/Master.php
  app/ViewItems/HTML/Master.php
Labels: refactor

#107 Converted all controls to have seperated page init methods
  app/Controllers/Config.php
  app/Controllers/DisplayLibrary.php
  app/Controllers/DisplaySeries.php
  app/Controllers/FirstTimeSetup.php
  app/Controllers/Home.php
  app/Controllers/Login.php
  app/Controllers/Reader.php
  app/index.php
Labels: refactor

#109 Changed everything to use the view service
  app/Controllers/Config.php
  app/Controllers/DisplayLibrary.php
  app/Controllers/DisplaySeries.php
  app/Controllers/FirstTimeSetup.php
  app/Controllers/Home.php
  app/Controllers/Login.php
  app/Controllers/Reader.php
  app/Services/View/Data/ViewItem.php
  app/Services/View/Provider.php
  app/Services/View/Service.php
  app/index.php
Labels: refactor

#110 Removed a bunch of old stuff
  app/Core/MetaPage.php
  app/ViewItems/PageViews/ConfigView.php
  app/ViewItems/PageViews/DisplayLibraryView.php
  app/ViewItems/PageViews/DisplaySeriesView.php
  app/ViewItems/PageViews/FirstTimeSetupView.php
  app/ViewItems/PageViews/HomeView.php
  app/ViewItems/PageViews/LoginView.php
  app/ViewItems/PageViews/MetaView.php
  app/ViewItems/PageViews/ReaderPageView.php
  app/ViewItems/PageViews/ReaderStripView.php
  app/ViewItems/Partial/BookcaseSeries.php
  app/ViewItems/ViewTemplate.php
  app/resources/img/meta_cover_01.jpg
  app/resources/img/options_cog.png
  app/resources/img/test_cover_01.jpg
  app/resources/img/test_cover_02.jpg
  app/resources/img/test_spine_01.jpg
  app/resources/img/test_spine_02.jpg
  app/resources/img/test_spine_03.jpg
  app/resources/img/test_spine_04.jpg
  app/resources/img/test_spine_05.jpg
  app/resources/img/test_spine_06.jpg
  app/resources/img/test_spine_07.jpg
Labels: refactor
